### ISSUE TITLE
problem with python --apiscan 

### ISSUE THREAD

**Issue by Vulnaholic** [nsnam/ns-3-dev-git#42]
I want to convert an existing module into python module but when I want to use for example `./waf --apiscan=core` there is an error like this:

``` Modules to scan:  ['core']
api-scan-gcc_LP64
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/user/ndnSIM/ns-3/bindings/python/wscript", line 386, in uid
    return self.uid_
AttributeError: 'apiscan_task' object has no attribute 'uid_'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/fardin/ndnSIM/ns-3/.waf3-2.0.9-897e824215d3dab2b64982d8af27db90/waflib/Runner.py", line 58, in run
    self.spawner.master.process_task(self.task)
  File "/home/fardin/ndnSIM/ns-3/.waf3-2.0.9-897e824215d3dab2b64982d8af27db90/waflib/Runner.py", line 206, in process_task
    tsk.process()
  File "/home/fardin/ndnSIM/ns-3/.waf3-2.0.9-897e824215d3dab2b64982d8af27db90/waflib/Task.py", line 168, in process
    del self.generator.bld.task_sigs[self.uid()]
  File "/home/fardin/ndnSIM/ns-3/bindings/python/wscript", line 392, in uid
    up(self.target)
TypeError: Unicode-objects must be encoded before hashing
```
How can I resolve this problem so I can convert the module automatically?

**Comment by TommyPec** [comment]
Hi,

it depends on what ns-3 version you're using. Some of them are not python3-savvy.
As a side note, I notice that you're using ndnSIM, which is _not_ under our control.

T.
